apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: unifiedui
    newName: 018881300778.dkr.ecr.eu-north-1.amazonaws.com/unifiedui
    # Deployed image tag is Git-driven (pure GitOps).
    # Update this value (commit + push), then Argo CD will roll out the new image.
    newTag: 3b571eec

patches:
  - target:
      kind: Ingress
      name: unified-ui
    patch: |-
      - op: add
        path: /spec/rules/-
        value:
          host: serviceplatform.mmg-nova.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: unified-ui
                    port:
                      name: http
  - target:
      kind: Deployment
      name: unified-ui
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: unified-ui-env
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: development
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SALES_MODULE_URL
          value: http://proposal-bot.backends.svc.cluster.local:8000
