apiVersion: v1
kind: Service
metadata:
  name: security-service
  labels:
    app.kubernetes.io/name: security-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: security-service
  ports:
    - name: http
      port: 8002
      targetPort: http

