apiVersion: v1
kind: Service
metadata:
  name: asset-management
  labels:
    app.kubernetes.io/name: asset-management
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: asset-management
  ports:
    - name: http
      port: 8001
      targetPort: http
