apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller.yaml
  - assetmgmt-dev.yaml
  - unifiedui-dev.yaml
  - sales-dev.yaml
  - security-dev.yaml
  - videocritique-dev.yaml
