apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

images:
  - name: unifiedui
    newName: 018881300778.dkr.ecr.eu-north-1.amazonaws.com/unifiedui
    # Deployed image tag is Git-driven (pure GitOps).
    newTag: d68186ee

patches:
  - target:
      kind: Deployment
      name: unified-ui
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: unified-ui-env
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: staging
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SALES_MODULE_URL
          value: http://proposal-bot.backends.svc.cluster.local:8000
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SECURITY_SERVICE_URL
          value: http://security-service.backends.svc.cluster.local:8002
