apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller.yaml
  - cluster-autoscaler-staging.yaml
  - assetmgmt-staging.yaml
  - unifiedui-staging.yaml
  - sales-staging.yaml
  - security-staging.yaml
  - videocritique-staging.yaml

