apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller.yaml
  - cluster-autoscaler-production.yaml
  - assetmgmt-production.yaml
  - unifiedui-production.yaml
  - sales-production.yaml
  - security-production.yaml
  - videocritique-production.yaml

