apiVersion: v1
kind: Service
metadata:
  name: video-critique
  labels:
    app.kubernetes.io/name: video-critique
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: video-critique
  ports:
    - name: http
      port: 8003
      targetPort: http

