apiVersion: v1
kind: Service
metadata:
  name: proposal-bot
  labels:
    app.kubernetes.io/name: proposal-bot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: proposal-bot
  ports:
    - name: http
      port: 8000
      targetPort: http

