apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

secretGenerator:
  - name: gitlab-ironforge-repo
    behavior: create
    envs:
      - gitlab-repo.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
  labels:
    argocd.argoproj.io/secret-type: repository

