apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: proposal-bot
    newName: 018881300778.dkr.ecr.eu-north-1.amazonaws.com/proposal-bot
    # Deployed image tag is Git-driven (pure GitOps).
    # This is updated by CI via Merge Request (see `gitops_mr_sales_dev`).
    newTag: 87e0c4c7

patches:
  - target:
      kind: Deployment
      name: proposal-bot
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: proposal-bot-env
