apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

images:
  - name: proposal-bot
    newName: 018881300778.dkr.ecr.eu-north-1.amazonaws.com/proposal-bot
    # Deployed image tag is Git-driven (pure GitOps).
    # This is updated by CI via Merge Request (see `gitops_mr_sales_dev`).
    newTag: d1662e45

patches:
  - target:
      kind: Deployment
      name: proposal-bot
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: proposal-bot-env
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ASSET_MGMT_URL
          value: http://asset-management.backends.svc.cluster.local:8001
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload: sales
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: dedicated
            operator: Equal
            value: sales
            effect: NoSchedule
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/failureThreshold
        value: 6
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
        value: 10
